# Hjem-managed dotfiles for Coder workspaces.
#
# This is a Hjem module (module class "hjem"), *not* a Home Manager module. It
# is evaluated by `hjemConfigurations.<username>` in flake.nix and applied with
# `just hjem-switch`. Option reference: https://hjem.feel-co.org/options.html
#
# Targets are relative to $HOME (`files`) or the matching XDG directory
# (`xdg.config.files`, `xdg.data.files`, ...). Keep paths disjoint from what
# Home Manager writes — both link into $HOME and neither knows about the other.
#
# Declaring files by hand looks like this:
#
#   files.".foo".source = ./dotfiles/foo;
#   files.".bar".text = "hello";
#   xdg.config.files."baz.json" = {
#     generator = lib.generators.toJSON { };
#     value.foo = 1;
#   };
#
# New files must be `git add`ed before `just hjem-switch` can see them — the
# manifest is built from this repo as a git flake.
{ lib, ... }:
let
  # Link a whole directory tree, one file at a time, preserving relative paths.
  # Per-file entries (rather than symlinking the directory) leave room for Home
  # Manager to own individual files in the same directory.
  linkTree =
    root: prefix:
    lib.listToAttrs (
      map (
        path:
        lib.nameValuePair "${prefix}/${lib.removePrefix "${toString root}/" (toString path)}" {
          source = path;
        }
      ) (lib.filesystem.listFilesRecursive root)
    );

  fishFiles = linkTree ./dotfiles/fish "fish";
in
{
  # ~/.config/fish/{conf.d,functions,completions}. `config.fish` stays with Home
  # Manager (modules/programs/fish.nix), which is what generates the eza/fzf/
  # direnv/gpg/try integrations and the `nx` wrapper.
  xdg.config.files = fishFiles;

  assertions = [
    {
      assertion = !(fishFiles ? "fish/config.fish");
      message = ''
        ~/.config/fish/config.fish is generated by Home Manager
        (modules/programs/fish.nix). Remove it from
        hosts/linux/coder/dotfiles/fish or the two will fight over the file.
      '';
    }
  ];
}
